name: 'SubmitSigningRequest'
description: ''
inputs:
  SignPathConnectorUrl:
    description: 'GitHub Actions SignPath connector URL'
    required: true
  CIUserToken:
    description: 'SignPath REST API access token. More detailes: https://about.signpath.io/documentation/build-system-integration#authorization'
    required: true
  OrganizationId:
    description: 'SignPath organization id. More detailes: https://about.signpath.io/documentation/getting-started'
    required: true
  ProjectSlug:
    description: 'SignPath project slug. More detailes: https://about.signpath.io/documentation/projects'
    required: true
  SigningPolicySlug:
    description: 'SignPath signing policy slug. More detailes: https://about.signpath.io/documentation/projects#signing-policies'
    required: true
  ArtifactConfigurationSlug:
    description: 'SignPath artifact configuration id. More detailes: https://about.signpath.io/documentation/projects#artifact-configurations'
    required: true
  ArtifactName:
    description: 'Name of the artifact to sign'
    required: true
  GitHubToken:
    description: 'GitHub access token'
    required: true
  SignPathApiUrl:
    description: 'SignPath API base url'
    default: 'https://app.signpath.io'
runs:
  using: 'node16'
  main: 'dist/index.js'