name: 'SubmitSigningRequest'
description: ''
inputs:
  SignPathConnectorUrl:
    description: 'GitHub Actions SignPath connector URL'
    required: true
  ApiToken:
    description: 'SignPath REST API access token. More details: https://about.signpath.io/documentation/build-system-integration#authorization'
    required: true
  OrganizationId:
    description: 'SignPath organization id. More details: https://about.signpath.io/documentation/getting-started'
    required: true
  ProjectSlug:
    description: 'SignPath project slug. More details: https://about.signpath.io/documentation/projects'
    required: true
  SigningPolicySlug:
    description: 'SignPath signing policy slug. More details: https://about.signpath.io/documentation/projects#signing-policies'
    required: true
  ArtifactConfigurationSlug:
    description: 'SignPath artifact configuration id. More details: https://about.signpath.io/documentation/projects#artifact-configurations'
    required: true
  ArtifactName:
    description: 'Name of the artifact to sign'
    required: true
  SignedArtifactDestinationPath:
    description: 'Path where the signed artifact will be saved'
    required: false
  GitHubToken:
    description: 'GitHub access token'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'