name: 'Submit a Signing Request'
author: 'SignPath GmbH'
description: 'Submit a signing request to SignPath and download the signed artifact'
inputs:
  signPathConnectorUrl:
    description: 'GitHub Actions SignPath connector URL'
    required: true
  apiToken:
    description: 'SignPath REST API access token. More details: https://about.signpath.io/documentation/build-system-integration#authorization'
    required: true
  organizationId:
    description: 'SignPath organization id. More details: https://about.signpath.io/documentation/getting-started'
    required: true
  projectSlug:
    description: 'SignPath project slug. More details: https://about.signpath.io/documentation/projects'
    required: true
  signingPolicySlug:
    description: 'SignPath signing policy slug. More details: https://about.signpath.io/documentation/projects#signing-policies'
    required: true
  artifactConfigurationSlug:
    description: 'SignPath artifact configuration id. More details: https://about.signpath.io/documentation/projects#artifact-configurations'
    required: true
  artifactName:
    description: 'Name of the artifact to sign'
    required: true
  signedArtifactDestinationPath:
    description: 'Path where the signed artifact will be saved, if empty then the task will not download the artifact from SignPath'
    required: false
  gitHubToken:
    description: 'GitHub access token. Is is recommended to use the default token provided by GitHub: \${{ secrets.GITHUB_TOKEN }}'
    required: true
outputs:
  signingRequestId:
    description: 'The id of the newly created signing request'
  signingRequestWebUrl:
    description: 'The url of the signing request in SignPath'
  signPathApiUrl:
    description: 'The base API url of the SignPath API'
  signingRequestDownloadUrl:
    description: 'The url of the signed artifact in SignPath'
runs:
  using: 'node20'
  main: 'dist/index.js'