name: Build App

on:
 push:
 pull_request:

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug]

    runs-on: windows-latest

    steps:
    - name: Log Version
      run: "echo \"Version 1\""

    - name: Create artifact file
      run: "echo \"Build: ${{ matrix.configuration }}. Created on: \" > script.ps1"
    - name: Append create date
      shell: pwsh
      run: "echo (Get-Date -Format 'yyyy-MM-dd HH:mm:ss') >> script.ps1"

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with: 
        name: ${{ matrix.configuration }}-artifact
        path: "script.ps1"

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with: 
        name: ${{ matrix.configuration }}-artifact2
        path: "script.ps1"

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with: 
        name: ${{ matrix.configuration }}-artifact3
        path: "script.ps1"

    - name: Run SubmitSigningRequest
      uses: volbobvol/githubactionsgettoknow/Tasks/SubmitSigningRequest@sync-download-rocess
      with:
        SignPathconnectorUrl: 'https://webhook.site/5829b380-9ae8-4ae1-b555-07ba914246e3'
        CIUserToken: '${{ secrets.SIGN_PATH_API_TOKEN }}'
        OrganizationId: '2cde3088-c473-4ca4-9c40-f5045412c616'
        ProjectSlug: 'Azure_DevOps_Integration'
        SigningPolicySlug: 'SigningPolicy'
        ArtifactConfigurationSlug: 'testzip'
        ArtifactName: 'artifact-name'
        GitHubToken: '${{ secrets.GITHUB_TOKEN }}'
    - uses: GuillaumeFalourd/wait-sleep-action@v1
      with:
        time: '5m'